### ISSUE TITLE
Snakemake v 7.21 requires output file in rule all

### ISSUE THREAD

**Issue by dariarom94** [epigen/dea_limma#2]
without adding a completion marker file ({}_succesfully_completed.txt snakemake would never start reporting "nothing to be done" on version 7.21

**Comment by sreichl** [comment]
Hi Daria,
thanks for letting me know!

The latest Snakemake version seems to be the problem. Please try Snakemake version 7.15.2.
The workflow has been tested with this version. So it should work.

Cheers,
Stephan

PS: I am closing the issue, because I can not address it in the workflow.
