### ISSUE TITLE
Handle empty bed or features_annot.txt

### ISSUE THREAD

**Issue by fwzhao** [epigen/dea_limma#21]
Following split of dea_limma by direction, some of the resulting directional bed files and features_annot.txts end up empty.

This lead to errors when programmatically coming up with enrichment_analysis inputs.
Can also fix on the end of enrichment_analysis (to better handle empty files) particularly for GREAT. Empty features_annot.txts do not throw errors in enrichments.

Note that file sizes of empty .bed = 0 bytes, but  empty .txt != 0 bytes. So find <file> --size is not ideal.

**Comment by sreichl** [comment]
- [ ] consider where to address this and then implement and document decision e.g., empty files have to be generated for continuity and enrichment analysis should skip empty files
