### ISSUE TITLE
R environment not being set-up

### ISSUE THREAD

**Issue by burtonjake** [epigen/dea_limma#22]
If you run the pipeline without having already installed R then `Rscript` cannot be invoked and the rule [all] fails. The expected behaviour (from my perspective) is that the conda environment created for the rule should create an R environment (so r-base or r-essentials should be in the environment specification I guess?) as well as include all the required libraries (limma, edgeR). Alternatively it should be documented that R should be installed.

Tested that is is currently 'fixed' by installing R with `conda install r-base` first.

Related (or possibly another issue) is that the R libraries from the [environment specification](https://github.com/epigen/dea_limma/blob/main/workflow/envs/limma.yaml) aren't being found. If I add them manually to the environment in which I have both R and snakemake installed then the module runs. Which suggests the environment isn't being picked up for some reason.

---
`snakemake --version` : 7.32.4
dea_limma version : v1.0.3

**Comment by sreichl** [comment]
Thanks for reporting. This looks very fishy to me. what's the exact error message? @fwzhao has recently installed and used it without issues? R should NOT be in the Snakemake environment but in the environments for the respective rules that need R. limma for sure has it as dependency. Try the latest version of dea_limme i.e., v2.0.0. please.

**Comment by sreichl** [comment]
Okay that makes sense. Sounds like Snakemake 7 (--use-conda is deprecated in v8). Maybe makes sense to upgrade everything to also benefit from the latest module versions.
